dados = [
    "Qual é o maior jornal mágico da Grã-Bretanha?",
    "Profeta Diário",
    "De qual dos fantasmas de Hogwarts Pirraça tem medo?",
    "O Barão Sangrento",
    "Qual madeira de varinha é considerada azarada?",
    "Sabugueiro",
    "Quando foi fundado Olivaras?",
    "382 a.C.",
    "Qual é o contra-feitiço para Accio, o feitiço convocatório?",
    "Depulso",
    "Qual aula eletiva é ocasionalmente oferecida em Hogwarts?",
    "Alquimia",
    "O Feitiço Muffliato enche os ouvidos de seus alvos com o quê?",
    "Zumbido não identificável",
    "Qual é o efeito colateral do Petrificus Totalus?",
    "Membros enrijecidos",
    "Que encantamento torna um objeto à prova d’água?",
    "Impervius",
    "Quem escreveu Maldições e Contra-maldições?",
    "Viridiana",
    "Qual é o encantamento para o Feitiço da Memória?",
    "Obliviate",
    "Quem é o diretor da Corvinal?",
    "Professor Flitwick",
    "Qual o nome do poltergeist de Hogwarts?",
    "Pirraça",
    "Qual é o principal uso do encantamento Scourgify?",
    "Limpar",
    "Qual desses feitiços pode convocar um objeto?",
    "Accio",
    "Qual item no escritório do diretor permite que você revise memórias engarrafadas?",
    "A Penseira",
    "Qual é o nome do gato de Filch?",
    "Madame Nor-r-ra",
    "Se alguém desejasse aumentar o efeito do feitiço Bombarda, qual encantamento você usaria?",
    "Bombarda Maxima",
    "Em qual desses cenários você usaria o Cistem Aperio?",
    "Para explodir uma mala trancada",
    "Qual é o encantamento para o Feitiço Escudo?",
    "Protego",
    "Qual é o contra-feitiço para Colloportus?",
    "Alohomora",
    "Quem é a professora de Adivinhação?",
    "Professora Trelawney",
    "Qual NÃO é um efeito colateral de um feitiço de silenciamento mal lançado?",
    "Fome insaciável",
    "O encantamento Descendo pode fazer um objeto alvo fazer o quê?",
    "Descer",
    "Que encantamento marca o ar com uma trilha de fumaça?",
    "Flagrate",
    "Qual encantamento cancela todos os efeitos do feitiço?",
    "Finite Incantatem",
    "Qual é a única vila só de bruxos na Grã-Bretanha?",
    "Hogsmeade",
    "Quais criaturas guardam as árvores fabricantes de varinhas?",
    "Tronquilhos",
    "O que “Colloportus” faz?",
    "Fecha e tranca fechaduras",
    "Qual encanto congela o alvo no lugar?",
    "Immobulos",
    "Em qual desses cenários você usaria o Feitiço Muffliato?",
    "Para evitar ser ouvido",
    "Qual é o movimento da varinha para Wingardium Leviosa?",
    "Girar e sacudir",
    "Qual desses amuletos é a azaração dos pés dançantes?",
    "Tarantallegra",
    "Que feitiço terminamos na aula usando Finito Incantatem?",
    "Iluminação da varinha",
    "O que o Feitiço de Tricô encanta?",
    "As agulhas de tricô",
    "Qual outro nome para Defodio?",
    "Feitiço Gouging",
    "O que é um “Guardador de Segredo”?",
    "Uma pessoa a qual alguém confiou um segredo",
    "As faíscas azuis causam algum dano quando lançadas nas pessoas?",
    "Machuca apenas um pouco",
    "Qual feitiço silencia uma pessoa?",
    "Silencio",
    "O feitiço de extinguir pode apagar o fogo de um dragão?",
    "Sim",
    "Qual a língua nativa para os feitiços?",
    "Latin",
    "É seguro beber água conjurada pelo feitiço Aguamenti?",
    "Sim, é totalmente seguro",
    "Quem é o professor de Poções?",
    "Professor Severus Snape",
    "Qual é o nome do governo mágico da América?",
    "MACUSA",
    "Quem é o instrutor de voo?",
    "Madame Hooch",
    "Qual é o segundo trabalho da Madame Hooch?",
    "Árbitra de Quadribol",
    "O que você diz para invocar uma vassoura para a sua mão?",
    "Suba",
    "Qual destas NÃO É uma forma mágica de transporte?",
    "Voar na vassoura",
    "Quem é a professora de Herbologia?",
    "Professora Sprout",
    "O Pêndulo Estrela-do-Mar é uma tática usada por qual posição do Quadribol?",
    "Goleiro",
    "O que é uma Finta de Wronski?",
    "Fingir mergulhar para pegar o pomo",
    "Qual time de Quadribol só tem jogadoras mulheres?",
    "As Harpias de Holyhead",
    "O que aconteceu durante a Copa Mundial de Quadribol em 1473?",
    "Os jogadores cometeram todas as faltas",
    "De que cor é o guarda-chuva do Hagrid?",
    "Rosa",
    "Quanto tempo durou o maior jogo de Quadribol?",
    "Seis meses",
    "Qual é o maior evento de Quadribol?",
    "Copa do Mundo",
    "Quando a temporada de Quadribol começa?",
    "Setembro",
    "O Pomo de Ouro foi inventado para substituir qual criatura?",
    "Pomorim Dourado",
    "Eu *Mérula* sei quem é o Chefe Supremo. Você sabe?",
    "Albus Dumbledore",
    "Qual departamento do Ministério da Magia que regulariza o Quadribol?",
    "Jogos e Esportes Mágicos",
    "O que você precisa evitar nos seus olhos enquanto você voa?",
    "Insetos",
    "Quando o Quadribol foi inventado?",
    "1050 a.C",
    "Quantos times existem nas ligas britânicas e irlandesas de Quadribol?",
    "13",
    "O que te ajudará quando você for tentar uma travagem forte?",
    "Uma pegada forte",
    "Qual esporte mágico é popular na América do Norte?",
    "Trancabola",
    "Quais jogadores de Quadribol evitam os balaços?",
    "Os batedores",
    "Qual é o primeiro passo para fazer um Bell Tailslide?",
    "Voar direto para cima",
    "O que é necessário na manobra Levando Passageiros?",
    "Cooperação completa",
    "Qual é a maior bola do Quadribol?",
    "Goles",
    "Que tipo de bola tenta atingir os jogadores?",
    "Balaço",
    "Quantos pontos vale o Pomo de Ouro?",
    "150",
    "Quando você dirige para trás, como funciona a direção?",
    "Vire para a direção oposta",
    "Qual jogador de Quadribol marca pontos?",
    "Artilheiro",
    "Uma Firebolt é um tipo de quê?",
    "Vassoura",
    "Qual destes não é um tipo de vassoura?",
    "Occamy",
    "Onde acontecem as aulas de voo?",
    "Limites do castelo",
    "A Madame Hooch tem o quê em amarelo?",
    "Os olhos",
    "Pegar qual objeto termina com uma partida de Quadribol?",
    "Pomo de Ouro",
    "Uma Nimbus é um tipo de quê?",
    "Vassoura",
    "Quais destas não é um tipo de vassoura?",
    "Phoenix",
    "Qual destes é um mergulho geralmente usado por Apanhadores?",
    "Spiral Dive",
    "Qual time de Quadribol é o último da liga?",
    "Chudley Cannons",
    "Aposto que você não sabe quantos bruxos servem ao Ministério da Magia!",
    "50",
    "Você não vai saber essa. Diga um método que faz a sua vassoura voar mais rápido.",
    "Usar polidor",
    "Qual feitiço cria água?",
    "Aguamenti",
    "Qual livro detalha a história do Quadribol?",
    "Quadribol Através dos Séculos",
    "Em que ano aconteceu a primeira partida?",
    "1050 a.C",
    "Você sabe que tipo de criatura é um Bicho-Papão? Porque eu *Mérula* sei.",
    "Não-ser",
    "Ficaria surpresa se você soubesse disso. Qual é o primeiro passo para voar em sua varinha?",
    "Subir",
    "Onde fica a sede da Liga de Quadribol britânica e irlandesa?",
    "No Ministério da Magia",
    "De acordo com a Madame Hooch, qual destes aumenta a suas chances de cair para a sua morte? Talvez você deva considerar como uma sugestão.",
    "Ter cabelo longo",
    "Qual destes é necessário para chamar a sua vassoura com sucesso?",
    "Equilíbrio",
    "Como o Trancabola é diferente do Quadribol?",
    "As bolas explodem",
    "Quantos pontos valem um gol?",
    "10",
    "Qual forma de transporte mágico é ilegal?",
    "Tapetes voadores",
    "A técnica de chamar a vassoura permite que você faça o que enquanto voa?",
    "Lance feitiços",
    "Por que você precisaria trocar de vassouras enquanto está no ar?",
    "Falha na vassoura",
    "Quem esteve em todas as Copas do Mundo de Quadribol desde que nasceu?",
    "Mérula",
    "Nenhum feitiço já desenvolvido permite que um mago faça o quê?",
    "Voe sem ajuda",
    "Quem escreveu o livro Notas Mágicas e Poções?",
    "Arsenius Jigger",
    "Qual o tipo de caldeirão utilizado pelos alunos dos primeiros anos?",
    "Estanho",
    "Qual é a melhor forma de extrair suco de um Sopophorous Bean?",
    "Esmagando",
    "Qual a cor da poção do Sono sem Sonhos?",
    "Roxa",
    "O que faz a poção de Arrepiar Cabelos?",
    "Arrepia os cabelos",
    "A Poção Pepperup evoluiu de um remédio criado por qual mago do século 12?",
    "Linfred of Stinchcombe",
    "Quem já ocupou o posto de Snape como Mestre de Poções?",
    "Horace Slughorn",
    "A Seca Desinflante é um antídoto para qual poção?",
    "Solução de Inchaço",
    "A que tipo de poção pertence a Terceira Lei de Golpalott?",
    "Antídotos",
    "Com que idade você pode ganhar sua licença de aparatação?",
    "17",
    "Qual poção dá ao bebedor uma sorte incrível?",
    "Felix Felicis",
    "Qual é o cheiro da Amortentia?",
    "Depende",
    "Quantas escadas existem em Hogwarts?",
    "142",
    "Qual ingrediente não é utilizado na poção do encolhimento?",
    "Ovo podre",
    "Qual é um efeito não colateral do Elixir para induzir a euforia?",
    "Suor excessivo",
    "Quem escreveu “Criação de Poções Avançada”?",
    "Libatius Borage",
    "Que livro é instrumental para esta lição?",
    "Encante o seu próprio queijo",
    "Qual é o soro da verdade mais poderoso?",
    "Veritaserum",
    "O que não é um nome alternativo para Acônito?",
    "Belladona",
    "Qual é o principal uso da essência de Murtlap?",
    "Feridas calmantes",
    "Cite um dos ingredientes da poção Doxicida",
    "Fígado de dragão",
    "O que faz as fotos mágicas se moverem?",
    "Solução de desenvolvimento",
    "Qual poção faz com que o bebedor fale bobagens?",
    "Bebida balbuciante",
    "Qual é a finalidade da Poção para Tosse?",
    "Curar a tosse",
    "Qual é a utilidade de uma poção da paz?",
    "Acalmar o bebedor",
    "Quando foi fundada Hogwarts?",
    "Século X",
    "Qual é o efeito colateral da Poção Pepperup?",
    "Vapor vindo das orelhas",
    "Qual é o efeito da Poção Wideye?",
    "Manter você acordado",
    "Qual condição pode ser remediada por uma poção calmante?",
    "Choque",
    "Que tipo de poção é Weedosoros?",
    "Veneno",
    "Professor Snape é o diretor de qual casa de Hogwarts?",
    "Sonserina",
    "Se eu quisesse usar uma Poção para o Envelhecimento para me tornar significativamente mais velho, o que eu faria?",
    "Tomaria uma quantidade maior",
    "Quem inventou a poção capilar do Sleakeazy?",
    "Fleamont Potter",
    "Ao mexer uma Poção Wiggenweld, quantas vezes a solução mudará de cor durante o processo de agitação?",
    "Várias vezes",
    "Qual ingrediente Snape nos faz esmagar em uma Poção Wideye?",
    "Presas de cobra",
    "Quem é o autor de “Poções Mui Potentes”?",
    "Phineas Bourne",
    "Qual dessas opções descreve melhor a Casa Sonserina?",
    "Engenhosa",
    "O que é ensinado nesta aula?",
    "Uma ciência sutil",
    "Quais ingredientes “selam” uma mordida de lobisomem?",
    "Prata e dítamo",
    "O que é aritmancia?",
    "Numerologia",
    "O que é notável sobre os elixires eternos?",
    "Eles nunca acabam",
    "Qual dos seguintes tipos de sangue de réptil é usado na Poção Wiggenweld?",
    "Salamandra",
    "Qual poção é comumente apresentada nos contos de fadas trouxas?",
    "Poção do Morto-Vivo",
    "Qual ingrediente do Depósito de Poções Snape pediu que você recuperasse para restaurar os pontos da Casa?",
    "Lesmas em conserva",
    "Qual a cor do gás Garroting?",
    "É incolor",
    "Pergunta:Qual o sabor do Veritaserum?",
    "Não há nenhum sabor",
    "Qual desses elementos não influencia na transfiguração?",
    "Cor",
    "Qual desses não é uma forma de transfiguração?",
    "Encantamento",
    "O que torna a transfiguração mais fácil?",
    "Aparência semelhante",
    "Os alunos de Transfiguração praticam transformar qual inseto em botões?",
    "Besouros",
    "O que Reparifarge faz?",
    "Desfaz transfigurações",
    "Qual feitiço transforma um objeto em pedra?",
    "Duro",
    "Qual feitiço desmascarou Gerardo Grindelwald em 1926?",
    "Revelio",
    "Que feitiço faz os objetos desaparecerem?",
    "Evanesco",
    "Uma estátua de que criatura marca a entrada para o escritório do diretor?",
    "Gárgula",
    "Qual sub ramo da transfiguração é considerado o mais difícil?",
    "Transfiguração Humana",
    "Qual propriedade você deve contabilizar na transfiguração?",
    "Peso",
    "O que fazem os feitiços de troca?",
    "Trocam objetos um pelo outro",
    "Qual feitiço é usado para consertar objetos quebrados?",
    "Reparo",
    "Em nossa primeira aula de Transfiguração, a Professora McGonagall nos mostrou um caldeirão Transfigurado. O caldeirão exibia que característica estranha?",
    "Orelhas de gato",
    "Feitiços de troca transfiguram quantos objetos ao mesmo tempo",
    "Dois",
    "Qual é o encantamento do feitiço de esfregar?",
    "Scourgify",
    "Qual afirmação é verdadeira sobre objetos conjurados?",
    "Eles se desfazem com o tempo",
    "Que tipo de transfiguração transforma um pintassilgo em um pomo de ouro?",
    "Transformação",
    "Qual feitiço duplica um item?",
    "Geminio",
    "Qual é o ramo da magia que lida com a alteração da forma ou aparência de um objeto?",
    "Transfiguração",
    "Nomeie um objeto para o qual transfiguramos um porco-espinho",
    "Almofada de alfinetes",
    "O que “Avis” conjura?",
    "Pássaros",
    "Quais dessas tarefas não podem ser auxiliadas por um Feitiço de Desaparecimento?",
    "Dançar",
    "Colovaria também é conhecido como o quê?",
    "Amuleto para Mudança de Cor",
    "O que o Colovaria faz?",
    "Muda a cor de algo",
    "Uma transformação pretendida é diretamente influenciada por qual dos seguintes?",
    "Concentração",
    "Quantos alunos dormem em cada dormitório?",
    "5",
    "Qual encantamento muda a cor do cabelo de uma pessoa?",
    "Crinus Muto",
    "O que o encantamento “Incarcerous” conjura?",
    "Cordas de amarração",
    "Qual encantamento conjura flores?",
    "Orchideous",
    "Qual deste feitiço é usado para transfigurar e se transformar em um coelho?",
    "Lapifors",
    "Quem é o autor do “Guia para Transfigurações para Iniciantes”?",
    "Switch Emeric",
    "O que “Serpensortia” conjura?",
    "Serpentes",
    "Para onde vão os itens desaparecidos?",
    "Para o não ser",
    "O que é um animago?",
    "Uma pessoa com forma animal",
    "Qual item não pode ser conjurado?",
    "Comida",
    "O que é verdade sobre gerbils?",
    "Eles gostam de escavar",
    "Qual a verdade sobre as tartarugas?",
    "Algumas vivem mais de 200 anos",
    "O boliche data de qual civilização antiga?",
    "Egito antigo",
    "Qual o oposto de uma conjuração?",
    "Desaparecimento",
    "Qual dos seguintes feitiços não é usado na aula de Transfiguração?",
    "Confundo",
    "Qual destas poções não contém ramos de Valeriana?",
    "Poção Polissuco",
    "Qual planta te ajuda a respirar debaixo d’água?",
    "Guelricho",
    "Quem é o Guardião das Chaves de Hogwarts?",
    "Rubeus Hagrid",
    "O que cobre a folha de urtiga?",
    "Pequenos pêlos que funcionam como agulhas",
    "A Professora Sprout é diretora de qual casa de Hogwarts?",
    "Lufa-Lufa",
    "Que criatura protege as Wiggentrees?",
    "Tronquilho",
    "Onde são cultivados os Shrivelfigs da mais alta qualidade?",
    "Abissínia",
    "Uma infusão de absinto NÃO é um ingrediente de qual dessas poções?",
    "Poção de Embelezamento",
    "O Ditamno é usado principalmente para qual propósito?",
    "Cura",
    "Quais dessas plantas florescem instantaneamente?",
    "Feijões Luzidios",
    "O que pode fazer com que o Patrono de alguém mude de forma?",
    "Grandes acontecimentos",
    "Que planta mágica lembra um toco de árvore ressecado?",
    "Arapucoso",
    "Quantos anos tem o Professor Snape?",
    "Por volta de 30",
    "Qual poção contém sanguinária?",
    "Poção Polissuco",
    "Gerânios com presas são mais notáveis ​​por quê?",
    "Suas presas",
    "Para quê é usado o pus de Bubotuber?",
    "Tratar a acne",
    "Onde a Descurainia pode ser encontrada?",
    "Na Floresta Proibida",
    "Onde a Valeriana cresce melhor?",
    "No sol",
    "Qual planta produz uma seiva fedorenta?",
    "Mimbulus Mimbletonia",
    "Por que você não deve derrubar feijões luzidios?",
    "Eles vão florescer",
    "Qual feitiço você deve usar para conter o Visgo do Diabo?",
    "Incendio",
    "Essa é fácil. Diga o nome de uma planta mágica cuja raízes podem ser usadas em várias poções.",
    "Valeriana",
    "Quais são as condições ideais para o crescimento do Visgo do Diabo?",
    "Escuro e úmido",
    "Onde a planta Sopóforo cresce?",
    "Pântanos sombrios.",
    "Qual é o fluído verde fedorento produzido pela Mimbulus Mimbletonia?",
    "Escrofulária",
    "É seguro comer bagas de visgo?",
    "Não, elas são venenosas.",
    "Com que frequência as flores da Fluttery Bush florescem?",
    "Uma vez por século",
    "Qual destas plantas tem propriedades de cura?",
    "Ditamno",
    "Qual destas plantas é uma substância proibida de Classe C?",
    "Venomous Tentacula",
    "A Mimbulus Mimbletonia solta qual substância?",
    "Escrofulária",
    "Quem ensina Trato das Criaturas Mágicas?",
    "Silvanus Kettleburn",
    "Onde os alunos de primeiro ano têm aula de Herbologia?",
    "Na estufa",
    "Qual parte da Mandrágora pode ser fatal?",
    "O seu grito",
    "Qual planta trata a acne?",
    "Bubotuber",
    "Qual é um outro nome para a Beladona?",
    "Deadly Nightshade",
    "Screechsnaps são capazes de fazer qual das seguintes opções?",
    "Mover e fazer barulho",
    "Como você sabe se uma porta está sob o efeito do Feitiço Imperturbável?",
    "Tente colocar coisas nela",
    "Onde os monges cultivam árvores resistentes à gravidade?",
    "Nepal",
    "Onde fica o dormitório da Lufa-Lufa?",
    "Próximo à cozinha",
    "Qual planta com cheiro doce muda de perfume?",
    "Flutterby Bush",
    "Qual é o nome da loja de travessuras em Hogsmeade?",
    "Zonko’s",
    "O que acontece quando você toca em um Wiggentree?",
    "Fica protegido contra criaturas das trevas",
    "Você deve cobrir os seus ouvidos quando essa planta madura começar a gritar. Qual é a planta?",
    "Mandrágora",
    "O Bulbo Bouncy é extremamente difícil de…",
    "Plantar",
    "Qual dessas plantas não morde?",
    "Salgueiro Lutador",
    "O que um Auror faz?",
    "Captura bruxos das trevas",
    "Qual poção tem Botão-de-prata?",
    "Poção do Desespero",
    "O que você pode neutralizar consumindo Moly?",
    "Encantamentos.",
    "Qual não é uma forma de dança?",
    "Staccato",
    "Qual é o sinal que revela que as mandrágoras amadureceram?",
    "Elas se movem para os vasos uma das outras",
    "Qual planta fofa produz feijões coloridos?",
    "Vagens Rosadas",
    "Qual parte da planta asphodel é usada para fazer a poção do Morto-Vivo?",
    "A raiz",
    "Como é chamado o coletivo de Tronquilhos?",
    "Ramo",
    "Qual destes feitiços não faz com que algo fique menor?",
    "Reducto",
    "Acromântula é o nome para uma versão maior de qual criatura?",
    "Aranha",
    "O veneno de lesmalenta é uma das substâncias que matam qual espécie invasiva?",
    "Toletes",
    "Quem foi a primeira bruxa ou bruxo a criar um basilisco?",
    "Herpo, o Sujo",
    "Qual criatura é conhecida por sua cleptomania?",
    "Pelúcio",
    "O que os vermes-cegos comem?",
    "Alface",
    "Qual dragão não é nativo da Grã-Bretanha?",
    "O Meteoro-Chinês",
    "Onde fica o habitat dos Glumbubles?",
    "Em lugares escuros e isolados",
    "Qual destes seres não vive nas propriedades de Hogwarts?",
    "Goblins",
    "O que diferencia o Knarl do ouriço?",
    "Sua natureza única",
    "O que a classificação X significa?",
    "Entediante",
    "Acredita-se que o Oraqui-Oralá seja qual pássaro trouxa extinto?",
    "O Dodô",
    "Onde fica a reserva de dragões mais próxima?",
    "Romênia",
    "Como você cumprimenta um Hipogrifo?",
    "Com uma reverência",
    "Os testrálios são erroneamente considerados presságios de quê?",
    "Infortúnio",
    "Qual é a melhor solução para um nariz quebrado?",
    "Episkey",
    "Qual feitiço tem o efeito oposto ao Lumus?",
    "Nox",
    "Os Amassos são mais parecidos com qual animal?",
    "Gato",
    "Qual feitiço te protege das aranhas?",
    "Arania Exumai",
    "Como é o sistema de classificação do Ministério da Magia?",
    "Com base no nível de periculosidade de uma criatura",
    "O que o melado de Glumbubles causa, se ingerido?",
    "Melancolia",
    "Quando a domesticação de dragões foi proibida?",
    "Na Convenção Internacional de Bruxos de 1709",
    "O cabelo de qual criatura costuma ser tecido em capas de invisibilidade?",
    "Seminviso",
    "Com o que você alimenta um dragão recém-nascido?",
    "Com um balde de conhaque misturado com sangue de galinha",
    "Qual encantamento pode afastar um Lethiford?",
    "O Feitiço do Patrono",
    "Onde é usada a plumagem do Fiuum?",
    "Em canetas",
    "Quem criou os famosos núcleos de varinha com chifres de lebrílopes?",
    "Isolt Sayre",
    "Por qual outro nome o Diabrete é comumente conhecido?",
    "Fada Mordente",
    "Qual característica a Occamy oferece?",
    "Choranaptyxis",
    "Qual feitiço é uma das Maldições Imperdoáveis?",
    "Crucio",
    "Que tipo de Ghoul é capaz de se disfarçar?",
    "Ghouls Camaleões",
    "Qual é o termo para um objeto feito com um fragmento da alma de um mago?",
    "Horcrux",
    "O que a Defesa Contra as Artes das Trevas precisa ser?",
    "Versátil",
    "Quem é a professora de Astronomia?",
    "Professora Sinistra",
    "Qual é uma das formas de rebater uma Azaração?",
    "Salvio Hexia",
    "Como você descreveria a voz de um Diabrete?",
    "Estridente",
    "Quando meus colegas e eu fundamos Hogwarts?",
    "Século 10",
    "O que a Azaração do Tropeço faz com a vítima?",
    "Cair",
    "Lançar Fumos cria que tipo de nuvem defensiva?",
    "De fumaça",
    "Qual é o encantamento para a Azaração da Língua Presa?",
    "Mimblewimble",
    "O que a Maldição Ear-Shrivelling faz?",
    "Aumenta o tamanho das orelhas",
    "Algumas maldições são até capazes de fazer o quê?",
    "Atingir gerações",
    "Vipera Evanesca é usada para desaparecer com qual tipo de criatura?",
    "Cobra",
    "Qual é o objetivo desta aula?",
    "Aperfeiçoar as suas habilidades",
    "Você sabe qual poção é eficiente contra Banshees?",
    "A Poção do Riso",
    "O que diferencia Ghouls Camaleões dos Ghouls habituais?",
    "Sua habilidade de mudar de forma",
    "Onde os Kappas são geralmente encontrados?",
    "No Japão",
    "O que o Feitiço Impedimenta faz?",
    "Paralisa temporariamente um alvo",
    "Você precisa pensar no que para conjurar o Feitiço do Patrono?",
    "Em uma lembrança forte e feliz",
    "Quem é o zelador de Hogwarts?",
    "Filch",
    "Os Feitiços das Trevas precisam do que para serem bem sucedidos?",
    "Más intenções",
    "Qual destas NÃO é uma Criatura das Trevas?",
    "Caranguejo-de-fogo",
    "Qual destes feitiços defensivos é o mais poderoso?",
    "Feitiço do Patrono",
    "Os professores de Defesa Contra as Artes das Trevas costumam durar quanto tempo?",
    "Um ano",
    "Quem é o autor de Pragas e Contrapragas?",
    "Vindictus Viridian",
    "O que faz o Cave Inimicum?",
    "Oculta presenças",
    "Qual é o melhor lugar para conseguir repelente de lesmas carnívoras?",
    "Beco Diagonal",
    "O que o Feitiço Imperturbável bloqueia?",
    "Sons",
    "O que o Feitiço do Alongamento faz?",
    "Faz com que o alvo se estenda",
    "Por quanto tempo “Você sabe quem” esteve no poder?",
    "11 anos",
    "Quando “Aquele que não deve ser nomeado” foi derrotado?",
    "Halloween",
    "O Congresso Medieval de Bruxos Europeus concede qual prêmio?",
    "Prêmio de Bravura Contra Animais Fantásticos",
    "O Congresso Medieval de Bruxos Europeus tem relação com qual convenção?",
    "Convenção Internacional de Bruxos",
    "Quando o Código de Conduta do Lobisomem foi desenvolvido?",
    "1637",
    "O que aconteceu após a Nevasca de Sabão de 1378?",
    "Uma explosão da bolha econômica bruxa",
    "Qual é a marca registrada de Godric Gryffindor?",
    "Espada",
    "Qual Ministro da Magia renunciou ao cargo com a Rebelião dos Duendes de 1752?",
    "Albert Boot",
    "Qual é a minha especialidade?",
    "Entediar os estudantes",
    "Quem é o fantasma da Sonserina?",
    "O Barão Sangrento",
    "Qual é o traço que Godric Gryffindor mais valoriza em um aluno?",
    "Coragem",
    "Quando o Pomo de Ouro foi introduzido pela primeira vez no Quadribol?",
    "1269",
    "Quem foi o primeiro Ministro da Magia?",
    "Ulick Gamp",
    "Eu *Nick-Quase-Sem-Cabeça* sou o fantasma de qual casa?",
    "Grifinória",
    "Quem era o dono original do Chapéu Seletor?",
    "Godric Gryffindor",
    "Qual é a marca registrada de Salazar Sonserina?",
    "Medalhão",
    "Pegunta: Quem é o fantasma da Lufa-Lufa?",
    "O Frei Gorducho",
    "Qual é a minha *Rowena Ravenclaw* marca registrada?",
    "Diadema",
    "Qual livro foi escrito por Beedle, o Bardo?",
    "Os Contos de Beedle, o Bardo",
    "Qual é a marca registrada de Helga Hufflepuff?",
    "Taça",
    "Quando foi escrita a primeira descrição de um jogo de Quadribol?",
    "1398",
    "Quem criou o Estatuto Internacional de Sigilo em Magia?",
    "A Confederação Internacional dos Bruxos",
    "Quando os meus *Rowena Ravenclaw* colegas e eu fundamos Hogwarts?",
    "Século 10",
    "Qual destes NÃO é um tipo de Magia das Trevas?",
    "Encantos",
    "Qual destes NÃO é um motivo para um mago permanecer na Terra como fantasma?",
    "Fome",
    "Como são todas as Convenções de Bruxos?",
    "Confidenciais e importantes",
    "Qual destes foi um motivo para que as queimadas às bruxas do século 14 tenham sido inúteis?",
    "Feitiço Glacius",
    "Elfric, the Eager foi responsável pelo quê?",
    "Uma revolta",
    "Pelo que eu *Nick-Quase-Sem-Cabeça* sou mais conhecido?",
    "Meu Pescoço Parcialmente Cortado",
    "Qual é o termo americano para Trouxas?",
    "Não-Mágicos",
    "O que o Pirraça faria em um julgamento?",
    "Algum erro",
    "Emerico, o Mal foi morto em um duelo contra qual bruxo?",
    "Egberto, o Notável",
    "Qual é o meu *Pirraça* local favorito para nadar?",
    "Nos banheiros masculinos no térreo",
    "Quem era o Ministro da Magia durante a Primeira Grande Guerra Bruxa?",
    "Archer Evermonde",
    "Em que época Wendelin, a Esquisita estava viva?",
    "Durante a Idade Média",
    "Que doce causa soluço?",
    "Hiccough Sweet",
    "A expressão “gatos selvagens” se refere ao quê?",
    "Às gárgulas em greve",
    "O que a Confederação Internacional dos Bruxos assinou em 1692?",
    "O Estatuto Internacional de Sigilo em Magia",
    "Em que ano aconteceu a Greve das Gárgulas?",
    "1911",
    "Os Trouxas também usavam runas antigas?",
    "Sim",
    "Qual desses livros fala sobre runas antigas?",
    "Silabário de Spellman",
    "Urico, o Esquisitão era conhecido por usar o que na cabeça?",
    "Uma água-viva",
    "Qual membro do Conselho se tornou o primeiro Ministro da Magia?",
    "Ulick Gamp",
    "Quem é o fantasma da Corvinal?",
    "A Dama Cinzenta",
    "Onde Beedle, o Barbo nasceu?",
    "Yorkshire, Inglaterra",
    "Os dentes de quem eu *Nick-Quase-Sem-Cabeça* acidentalmente transformei em presas, o que levou a minha morte?",
    "Lady Grieve",
    "Qual é o meu *Nick-Quase-Sem-Cabeça* nome completo?",
    "Nicholas de Mimsy-Porpington",
    "Quais espécies comandaram as Guerras Gigantes?",
    "Gigantes",
    "Eu *Pirraça* sou um gigante do quê?",
    "Travessuras",
    "Quem foi o primeiro árbitro de Quadribol a morrer em uma partida de Quadribol?",
    "Ciprião Youdlefoi",
    "Qual fantasma assombra o banheiro das garotas do segundo andar em Hogwarts?",
    "A Murta Que Geme",
    "O que Salazar Sonserina valorizava mais em um aluno?",
    "Astúcia",
    "Quando foi inaugurado Gringotes, o Banco dos Bruxos?",
    "1474",
    "A minha *Professor Binn* aula de História da Magia é focada no quê?",
    "Fatos",
    "Qual bruxo usou o Feitiço Tarantallegra em 79 d.C para conjurar uma dança dentro do Monte Vesúvio?",
    "Zaccaria Innocenti",
    "Onde o Professor Binns morreu?",
    "Em frente à lareira da sala dos funcionários",
    "De qual cor as chamas ficam com a presença de um fantasma?",
    "Azul",
    "Onde aconteceu a Rebelião dos Goblins de 1612?",
    "No vilarejo Hogsmeade",
    "Quem fundou o vilarejo Hogsmeade?",
    "Hengisto de Woodcroft",
    "Quando a Prisão de Azkaban foi aberta?",
    "1718",
    "O Código de Conduta do Lobisomem funcionou?",
    "Não",
    "Como os feiticeiros da Sardenha participaram da Convenção?",
    "Com um subcomitê",
    "O que o Pirraça faria na Convenção Internacional de Bruxos?",
    "O caos",
    "Como Elfric era conhecido?",
    "The Eager",
    "Quem criou o Estatuto Internacional de Sigilo em Magia?",
    "A Confederação Internacional dos Bruxos",
    "Onde aconteceu o Julgamento das Bruxas de 1692?",
    "Salém",
    "Em 1876, qual zelador tentou fazer com que eu *Pirraça* deixasse Hogwarts?",
    "Rancorous Carpe",
    "Como se chamam os bruxos que cooperam com os Trouxas?",
    "Feiticeiros",
    "Quantas vezes Wendelin, a Esquisita se deixou ser pega?",
    "Quarenta e sete",
    "O que fez com que Wendelin não fosse reconhecida?",
    "Ela usou disfarces",
    "O que substituiu o Conselho de Bruxos?",
    "O Ministério da Magia",
    "Quem liderou a Greve das Gárgulas?",
    "Um grupo de gárgulas selvagens",
    "Runas antigas possuem propriedades mágicas?",
    "Não",
    "Qual criatura foi protegida pelo Conselho de Bruxos?",
    "Pomorim Dourado",
    "Urico, o Esquisitão era de qual casa de Hogwarts?",
    "Corvinal",
    "Urico, o Esquisitão tem 50 pássaros mágicos de qual espécie?",
    "Agoureiros",
    "Quantas Pedras Filosofais existem?",
    "Uma",
    "Quem escreveu o livro “A Força Aérea da Coruja: Contos Verdadeiros da Guerra na Europa”?",
    "Simon Dentata",
    "Qual bruxa criou a cura para o Dragon Pox?",
    "Gunhilda de Gorsemoor",
    "Qual alquimista esteve na ativa durante a era medieval?",
    "Nicholas Flamel",
    "O que você encontrou enterrado na Cripta Maldita?",
    "O Tridente de uma sereia",
    "Qual NÃO é uma das linhas da palma da mão que lemos na Quiromancia?",
    "A linha do tempo",
    "Qual é o uso aceitável da Bola de Cristal?",
    "Para adivinhar o futuro",
    "A que se reduz o número 14?",
    "5",
    "O que usamos na Xilomancia?",
    "Galhos",
    "Onde você precisou ir para estudar a profecia da Trelawwey?",
    "No acampamento dos centauros",
    "Quem escreveu o Oráculo dos Sonhos?",
    "Inigo Imago",
    "Qual é o termo para uma bruxa ou bruxo que pode ver o futuro?",
    "Vidente",
    "Onde se original a Ovomancia?",
    "Na Grécia Antiga",
    "Quem mora na Floresta Proibida?",
    "Lobos inteligentes",
    "Qual espécie não-humana pratica a Adivinhação?",
    "Centauros",
    "Quem escreveu Desvendando o Futuro?",
    "Cassandra Vablatsky",
    "Ao praticar a Bibliomancia, qual passagem devemos selecionar?",
    "Uma passagem aleatória",
    "É considerado um bom presságio um pássaro voar em qual direção?",
    "Leste",
    "O que é o Sinistro?",
    "Um cão espectral",
    "Miomancia envolve a observação de qual criatura?",
    "Ratos",
    "O que torna a Lua tão brilhante no céu noturno?",
    "Ele reflete a luz do céu noturno",
    "A partir de qual evento medimos a idade do universo?",
    "O Big Bang",
    "Qual das seguintes opções é causada pelo clima espacial?",
    "Auroras",
    "Qual é o nome normalmente dado às chuvas de meteoros?",
    "Constelações",
    "Onde as constelações de nuvens escuras podem ser vistas com mais facilidade?",
    "No hemisfério sul",
    "Quantos planetas interestelares existem na Via Láctea?",
    "Bilhões",
    "O que causa o movimento noturno das estrelas pelo céu?",
    "A rotação da Terra"]

def adicionar(valor):
    dados.append(valor)

def imprimir():
    for i in dados:
        print(i)
